# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: document.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='document.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x64ocument.proto\"\xef\x01\n\x08\x44ocument\x12\x0e\n\x06\x64oc_id\x18\x01 \x02(\x03\x12\x1e\n\x05links\x18\x02 \x01(\x0b\x32\x0f.Document.Links\x12\x1c\n\x04name\x18\x03 \x03(\x0b\x32\x0e.Document.Name\x1a*\n\x05Links\x12\x10\n\x08\x62\x61\x63kward\x18\x01 \x03(\x03\x12\x0f\n\x07\x66orward\x18\x02 \x03(\x03\x1ai\n\x04Name\x12)\n\x08language\x18\x01 \x03(\x0b\x32\x17.Document.Name.Language\x12\x0b\n\x03url\x18\x02 \x01(\t\x1a)\n\x08Language\x12\x0c\n\x04\x63ode\x18\x01 \x02(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t')
)




_DOCUMENT_LINKS = _descriptor.Descriptor(
  name='Links',
  full_name='Document.Links',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='backward', full_name='Document.Links.backward', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='forward', full_name='Document.Links.forward', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=151,
)

_DOCUMENT_NAME_LANGUAGE = _descriptor.Descriptor(
  name='Language',
  full_name='Document.Name.Language',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='Document.Name.Language.code', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='country', full_name='Document.Name.Language.country', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=258,
)

_DOCUMENT_NAME = _descriptor.Descriptor(
  name='Name',
  full_name='Document.Name',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='language', full_name='Document.Name.language', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='Document.Name.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DOCUMENT_NAME_LANGUAGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=258,
)

_DOCUMENT = _descriptor.Descriptor(
  name='Document',
  full_name='Document',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='doc_id', full_name='Document.doc_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='links', full_name='Document.links', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Document.name', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DOCUMENT_LINKS, _DOCUMENT_NAME, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=258,
)

_DOCUMENT_LINKS.containing_type = _DOCUMENT
_DOCUMENT_NAME_LANGUAGE.containing_type = _DOCUMENT_NAME
_DOCUMENT_NAME.fields_by_name['language'].message_type = _DOCUMENT_NAME_LANGUAGE
_DOCUMENT_NAME.containing_type = _DOCUMENT
_DOCUMENT.fields_by_name['links'].message_type = _DOCUMENT_LINKS
_DOCUMENT.fields_by_name['name'].message_type = _DOCUMENT_NAME
DESCRIPTOR.message_types_by_name['Document'] = _DOCUMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Document = _reflection.GeneratedProtocolMessageType('Document', (_message.Message,), {

  'Links' : _reflection.GeneratedProtocolMessageType('Links', (_message.Message,), {
    'DESCRIPTOR' : _DOCUMENT_LINKS,
    '__module__' : 'document_pb2'
    # @@protoc_insertion_point(class_scope:Document.Links)
    })
  ,

  'Name' : _reflection.GeneratedProtocolMessageType('Name', (_message.Message,), {

    'Language' : _reflection.GeneratedProtocolMessageType('Language', (_message.Message,), {
      'DESCRIPTOR' : _DOCUMENT_NAME_LANGUAGE,
      '__module__' : 'document_pb2'
      # @@protoc_insertion_point(class_scope:Document.Name.Language)
      })
    ,
    'DESCRIPTOR' : _DOCUMENT_NAME,
    '__module__' : 'document_pb2'
    # @@protoc_insertion_point(class_scope:Document.Name)
    })
  ,
  'DESCRIPTOR' : _DOCUMENT,
  '__module__' : 'document_pb2'
  # @@protoc_insertion_point(class_scope:Document)
  })
_sym_db.RegisterMessage(Document)
_sym_db.RegisterMessage(Document.Links)
_sym_db.RegisterMessage(Document.Name)
_sym_db.RegisterMessage(Document.Name.Language)


# @@protoc_insertion_point(module_scope)
