# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='schema.proto',
  package='dremel',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cschema.proto\x12\x06\x64remel\"p\n\x06Schema\x12\x37\n\x10\x66ield_descriptor\x18\x01 \x03(\x0b\x32\x1d.dremel.SchemaFieldDescriptor\x12-\n\x0b\x66ield_graph\x18\x02 \x01(\x0b\x32\x18.dremel.SchemaFieldGraph\"n\n\x10SchemaFieldGraph\x12+\n\x04\x65\x64ge\x18\x01 \x03(\x0b\x32\x1d.dremel.SchemaFieldGraph.Edge\x1a-\n\x04\x45\x64ge\x12\x12\n\nfrom_field\x18\x01 \x01(\t\x12\x11\n\tto_fields\x18\x02 \x03(\t\"~\n\x15SchemaFieldDescriptor\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x10\n\x08\x63pp_type\x18\x02 \x01(\x05\x12\r\n\x05label\x18\x03 \x01(\x05\x12\x1c\n\x14max_repetition_level\x18\x04 \x01(\x05\x12\x18\n\x10\x64\x65\x66inition_level\x18\x05 \x01(\x05\x62\x06proto3')
)




_SCHEMA = _descriptor.Descriptor(
  name='Schema',
  full_name='dremel.Schema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field_descriptor', full_name='dremel.Schema.field_descriptor', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field_graph', full_name='dremel.Schema.field_graph', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=136,
)


_SCHEMAFIELDGRAPH_EDGE = _descriptor.Descriptor(
  name='Edge',
  full_name='dremel.SchemaFieldGraph.Edge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from_field', full_name='dremel.SchemaFieldGraph.Edge.from_field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_fields', full_name='dremel.SchemaFieldGraph.Edge.to_fields', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=248,
)

_SCHEMAFIELDGRAPH = _descriptor.Descriptor(
  name='SchemaFieldGraph',
  full_name='dremel.SchemaFieldGraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='edge', full_name='dremel.SchemaFieldGraph.edge', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SCHEMAFIELDGRAPH_EDGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=248,
)


_SCHEMAFIELDDESCRIPTOR = _descriptor.Descriptor(
  name='SchemaFieldDescriptor',
  full_name='dremel.SchemaFieldDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='dremel.SchemaFieldDescriptor.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpp_type', full_name='dremel.SchemaFieldDescriptor.cpp_type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label', full_name='dremel.SchemaFieldDescriptor.label', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_repetition_level', full_name='dremel.SchemaFieldDescriptor.max_repetition_level', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='definition_level', full_name='dremel.SchemaFieldDescriptor.definition_level', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=376,
)

_SCHEMA.fields_by_name['field_descriptor'].message_type = _SCHEMAFIELDDESCRIPTOR
_SCHEMA.fields_by_name['field_graph'].message_type = _SCHEMAFIELDGRAPH
_SCHEMAFIELDGRAPH_EDGE.containing_type = _SCHEMAFIELDGRAPH
_SCHEMAFIELDGRAPH.fields_by_name['edge'].message_type = _SCHEMAFIELDGRAPH_EDGE
DESCRIPTOR.message_types_by_name['Schema'] = _SCHEMA
DESCRIPTOR.message_types_by_name['SchemaFieldGraph'] = _SCHEMAFIELDGRAPH
DESCRIPTOR.message_types_by_name['SchemaFieldDescriptor'] = _SCHEMAFIELDDESCRIPTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Schema = _reflection.GeneratedProtocolMessageType('Schema', (_message.Message,), {
  'DESCRIPTOR' : _SCHEMA,
  '__module__' : 'schema_pb2'
  # @@protoc_insertion_point(class_scope:dremel.Schema)
  })
_sym_db.RegisterMessage(Schema)

SchemaFieldGraph = _reflection.GeneratedProtocolMessageType('SchemaFieldGraph', (_message.Message,), {

  'Edge' : _reflection.GeneratedProtocolMessageType('Edge', (_message.Message,), {
    'DESCRIPTOR' : _SCHEMAFIELDGRAPH_EDGE,
    '__module__' : 'schema_pb2'
    # @@protoc_insertion_point(class_scope:dremel.SchemaFieldGraph.Edge)
    })
  ,
  'DESCRIPTOR' : _SCHEMAFIELDGRAPH,
  '__module__' : 'schema_pb2'
  # @@protoc_insertion_point(class_scope:dremel.SchemaFieldGraph)
  })
_sym_db.RegisterMessage(SchemaFieldGraph)
_sym_db.RegisterMessage(SchemaFieldGraph.Edge)

SchemaFieldDescriptor = _reflection.GeneratedProtocolMessageType('SchemaFieldDescriptor', (_message.Message,), {
  'DESCRIPTOR' : _SCHEMAFIELDDESCRIPTOR,
  '__module__' : 'schema_pb2'
  # @@protoc_insertion_point(class_scope:dremel.SchemaFieldDescriptor)
  })
_sym_db.RegisterMessage(SchemaFieldDescriptor)


# @@protoc_insertion_point(module_scope)
